### ISSUE TITLE
Please update newest version to curse

### ISSUE THREAD

**Issue by EKE00372** [unix/Nioro#24]
Please push newest version to curse, for toc bump and translates, thank you!

**Comment by WittBulter** [comment]
It may take a few days (I don't have a Windows right now).
And let me know if you want release version on `curseforge`.

**Comment by unix** [comment]
@EKE00372 Let me know If you want release version on `curseforge`, i can invite you to be the admin on `curseforge`.
I'll close this issue, please notify me of any update.

**Comment by EKE00372** [comment]
Just need a release on curse because ppl usually dont update from github, even they wont notice newest version is here, I dont know you didnt push do curse until a TWOWer ask me about this.

So now the problem is, you cannot push release because you dont have windows? probably works fine because ~~actually no user~~ no issue feedback on curse
