### ISSUE TITLE
修改字体大小会导致字体越来越小

### ISSUE THREAD

**Issue by realmsg** [unix/Nioro#25]
比如把字体比例设置为0.9.接下来不论向左还是向右滑动，raidframes上的角色名字都会越来越小

**Comment by EKE00372** [comment]
`Interface/AddOns/Nioro/app.lua:131: hooksecurefunc(): CompactPartyFrame_UpdateVisibility is not a function`

**Comment by unix** [comment]
之前没有看到，新版本已经解决。

**Comment by unix** [comment]
cc @EKE00372  @realmsg
