### ISSUE TITLE
亂碼及與OmniCC共存時的顯示問題

### ISSUE THREAD

**Issue by TinyRudy** [unix/Nioro#26]
感謝作者開發此UI，有效的改善10.1框架增減益過小問題，但是以下兩點是我遇到的問題:

1.使用英文客戶端時候，隊伍中有簡體/繁體中文ID會出現方格狀的亂碼
2.同時使用OmniCC和Nioro時候，帶有層數的增益效果會和OmniCC的時間顯示衝突，導致難以看到顯示的數字。如:奶薩的大地盾

**Comment by unix** [comment]
亂碼、Icon 位置衝突的問題都是暴雪原生 UI 的問題，這裏提供幾個建議：
1. 使用英文客戶端時，默認就是無法展示簡體、繁體 ID，這受限與暴雪默認的字體方案。如果想要兼容簡體、繁體角色用戶，你可以修改魔獸世界的默認字體為多語言兼容種類。
2. 你可以適當調整 OmniCC 的時間顯示位置。Nioro 並沒有改動 Buff / Debuff 的展示邏輯，只是允許其縮放，Icon 本身的工作還是 Raid frame。

同時，你亦可暫時禁用 Nioro 來判斷問題的來源以及在遊戲中調試。
